DROP DATABASE IF EXISTS movie_db;
CREATE DATABASE movie_db;
USE movie_db;

CREATE TABLE movies(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
names VARCHAR(100) NOT NULL
);

CREATE TABLE reviews (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
movie_id INT,
FOREIGN KEY (movie_id)
REFERENCES movies(id)
ON DELETE SET NULL, 
review TEXT NOT NULL
);